### ISSUE TITLE
Cadence Sensor "Wahoo CADENCE EB25" does not work

### ISSUE THREAD

**Issue by Dieggu** [Sublimis/UrbanBiker#35] opened 2019-06-27 14:04 UTC
I have a LG G7 Thinq with Andorid 8.0, which does not support ANT+ (see my other request)

I therefore installed a new Cadence Sensor from Wahoo. The sensor supports Bluetooth and ANT+ and is detected correctly, but no Cadence is displayed when recording a ride.

Cadence recording works fine , when I use the standard "Wahoo Fitness" App.

According to request #17 I had expected the sensor works nicely.

I attach my latest ride files and a hardcopy of the sensor settings.

![Screenshot_2019-06-27-15-56-55](https://user-images.githubusercontent.com/48885090/60272766-0b916c00-98f5-11e9-9afa-769ca58e0c69.png)
[2019-06-26_16-49.track.zip](https://github.com/Sublimis/UrbanBiker/files/3335080/2019-06-26_16-49.track.zip)

**Comment by Sublimis** [comment] 2019-06-28 08:23
Hi Dieggu, this seems like a more common problem with Wahoo Cadence sensor: https://support.strava.com/hc/en-us/articles/206150744-Tips-for-recording-with-your-Wahoo-cadence-sensor. It seems like that particular sensor type fails to follow the exact standard/protocol for Speed&Cadence reporting, but it's hard to say where exactly (so we can find a workaround) without having one in our hands. Can you please help us with that?

If you can, please install this app from Nordic Semiconductor: https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp, find the sensor and connect to it with this app. When you are taken to the '**Client**' tab (please see the screenshot), click on the '**Cycling Speed and Cadence, UUID: 0x1816**' field, and click on the three arrows besides '**CSC Measurement**'. Then turn the crank a few times to see what happens. If everything works fine, '**Crank rev**' and '**Last crank event time**' values should increase. It would be best to send us your screenshot at this point.


![image](https://user-images.githubusercontent.com/3844660/60328331-5d3a0500-998e-11e9-9c86-5e8cb9578ea2.png)

**Comment by Dieggu** [comment] 2019-06-28 19:12
Hi Sublimis,
thanks for your prompt answers and questions. I will give you all the support i can :)

Regarding your general questions of the second mail:
- I have a brand-new LG G7 ThinQ, Android 8.0 and Snapdragon 845
- I do not use a speed sensor. I only use GPS
- App Version is v5.14 (2019-06-23) Pro+
- GPS update interval is Default
GPS-Settings:
- Autopause is "realtime"
- Stationary exercise is "Do not use GPS"
- GPS-Update settings is "deactivated"
- Recalculate speed is "enabled"

Regarding your questions of the first mail:
- I went through the Strava link you sent me.
- There was no other sensor connected.
- Anyhow, I removed all sensors (only Cadence Sensor was connected and had to be removed) and I then readded the Cadence Sensor outdoors.
- I started a test ride and it showed cadence in UrbanBiker. So it seems to work. Quite strange.

I will retest tomorrow on a longer ride.

In the meanwhile, I installed nRFConnect and I attach screen-shot and logfile. May be, this gives further information and help.

[Log_nRF-Connect_2019-06-28 205500.txt](https://github.com/Sublimis/UrbanBiker/files/3340502/Log_nRF-Connect_2019-06-28.205500.txt)
![Screenshot_nRF-Connect](https://user-images.githubusercontent.com/48885090/60365462-10cfe300-99e9-11e9-90be-dc4f4e555049.png)

**Comment by Dieggu** [comment] 2019-06-29 07:19
Retest today. Firstly I started my regular workout. No Cadence was displayed, only "--" was displayed. Also there is none of the cadence.svg-files in the export. 

After having finished the workout, I removed and reconnected the sensor. This time cadence seemed to work. I attach both logs:

[CadenceFail.track.zip](https://github.com/Sublimis/UrbanBiker/files/3341587/CadenceFail.track.zip)
[CadenceOK.track.zip](https://github.com/Sublimis/UrbanBiker/files/3341589/CadenceOK.track.zip)

Dieggu

**Comment by Sublimis** [comment] 2019-06-30 20:44
Thanks for your effort. Everything about the sensor appears to be fine, yet we see the sensor sometimes works and sometimes not. This non-deterministic behavior usually indicates some race condition (i.e. timing problem) in the code, thus we revised some timings in our Bluetooth connection code (i.e. increased some delays). This may or may not work, but we have no sensor to test this against (all of our sensors have always worked without problems).

If it's not too much trouble, please try with the newest beta version (v5.15b). You can get it from https://play.google.com/apps/testing/com.sublimis.urbanbiker. Connect with the sensor several times (e.g. more than 5 times) and spin the crank; if it works (shows cadence) every time, then the problem is probably solved. If it fails even once, then we must look elsewhere.

**Comment by Dieggu** [comment] 2019-07-01 18:51
I joined testing and look forward to doing some tests.
Small update: It seems measurement works fine, when I scan sensors in UrbanBiker prior to starting the training. So I think, if we test like proposed, it should always work, even with the current version. Thoughts?

**Comment by Sublimis** [comment] 2019-07-04 10:40
This is definitely not normal, and is most probably some fluke, as scanning before using the sensor shouldn't influence the sensor. In any case, the issue is possibly fixed in the latest beta dated 2019-07-03, but we'll wait for your confirmation before claiming that 🙂 👍. Just to be clear, the sensor should work normally _every time_ (i.e. on every connection), and without any special treatment (like scanning before use), for the issue to be considered as fixed.

**Comment by Dieggu** [comment] 2019-07-04 20:08
Weird. Currently I have the version of 2019-06-29.  My sensor worked stable at least for the last 4 rides. I have no clue what went wrong before. Anyhow, I will wait for Beta version of 2019-07-03. I would expect to receive it automatically as I joined the testing program. Correct?

**Comment by Dieggu** [comment] 2019-07-06 13:38
New version: v5.15 (2019-7-05).
Today, the sensor was not recognized. No cadence was reported. I then stopped the recording, searched for sensors and restarted the recording. From that time, cadence was recorded, I would say with correct values.

I start to think, the sensor is defect, as the activity light on the sensor never showed up.

Thoughts?
Dieggu

**Comment by Sublimis** [comment] 2019-07-11 12:49
We managed to reproduce the issue in the end, by quickly toggling the switch next to a sensor in the list, and doing this many times. In fact, different kinds of issues can be encountered this way if you are patient enough (at least in older app versions).

Research showed that these are all in fact caused by poor Bluetooth code on Android part, and various timing problems it suffers, as can be learned e.g. from [here](https://github.com/googlesamples/android-BluetoothLeGatt/issues/44). Misbehaving sensors can take part of the blame, but we feel Android should take care of such cases.

As we learn further, it's impossible to prevent ALL Android Bluetooth problems, especially with a variety of devices and versions out there. The best thing to do is to catch as many sensor errors as possible, and reconnect the sensor when such error is detected. Thankfully, all errors happen while connecting, not during normal operation. So once the sensor connects without any issue, it should work properly and stay connected for any extended period of time.

This is exactly what we've implemented in v5.16 ([beta published](https://play.google.com/apps/testing/com.sublimis.urbanbiker)), among some other minor things. Sensor connecting looks reliable and stable for now, even when the sensor enable switch is toggled fast. Now we just need some heavy testing to corroborate this.

**Comment by Dieggu** [comment] 2019-07-12 18:39
Cool. Your assumptions fit exactly my perceptions. I downloaded v5.16 and will test.

**Comment by Dieggu** [comment] 2019-07-19 16:52
So, after one week of testing with my bike, everything works fine. Up to now I did 9 tours and no problem at all.
Very often, the sensor works from the start. Sometimes (rarely) it takes up to 90 secs until cadence is shown. This is totally OK for me and shows (at least I think so) that your recovery algorithm works really fine.

IMHO, this is definitely ready for the public and this issue can be closed.

**Closed** 2019-09-07 14:55 UTC
Labels: Done.
